apiVersion: v1
kind: ServiceAccount
metadata:
  name: pilot-load
  namespace: pilot-load-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pilot-load
  namespace: pilot-load-test
  labels:
    app: pilot-load
spec:
  replicas: 50
  template:
    metadata:
      name: pilot-load
      annotations:
        sidecar.istio.io/inject: "false"
        prometheus.io/scrape: "true"
        prometheus.io/port: "8765"
      labels:
        app: pilot-load
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              namespaces: [istio-system]
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - istiod
              topologyKey: kubernetes.io/hostname
      # May take a while to shut down
      terminationGracePeriodSeconds: 2000
      containers:
      - name: pilot-load
        image: swr.ap-southeast-1.myhuaweicloud.com/yzz/pilot-load:parallel
        imagePullPolicy: IfNotPresent
        args:
          - "cluster"
          - "--pilot-address=istiod.istio-system:15010"
          - "--config=/etc/config/config/config.yaml"
        volumeMounts:
        - name: config
          mountPath: /etc/config/config
      volumes:
      - name: config
        configMap:
          name: pilot-load-config
      serviceAccountName: pilot-load
  selector:
    matchLabels:
      app: pilot-load

#
#  kubectl create clusterrolebinding pilot-load --clusterrole=cluster-admin --user=system:serviceaccount:default:pilot-load
